version: '3.8'

services:
  event-store-database:
    image: ghcr.io/bytemedrive/eventstoredb:dev-arm
    ports:
      - "2113:2113"
      - "1113:1113"

  postgres:
    image: postgres:14.7-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "byteme"
      POSTGRES_PASSWORD: "byteme0147"
      POSTGRES_DB: "byteme"
    volumes:
      - byteme-postgres-database-volume:/var/lib/postgresql/data

  backend:
    image: ghcr.io/bytemedrive/backend:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      ESDB_HOSTNAME: "event-store-database"
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/byteme
    depends_on:
      - event-store-database
      - postgres

volumes:
  byteme-postgres-database-volume: